/**
 * Authentication routes for Audacious Money platform
 *
 * Handles user signup, login, email verification, and password reset
 */

import { Hono } from 'hono';
import crypto from 'crypto';
import type { HonoEnv } from '../types/hono.js';
import {
  validate,
  signupSchema,
  loginSchema,
  passwordResetRequestSchema,
  passwordResetSchema,
} from '../utils/validation.js';
import { hashPassword, timingSafeVerify } from '../utils/password.js';
import { generateUserToken } from '../utils/jwt.js';
import {
  created,
  conflict,
  badRequest,
  unauthorized,
  forbidden,
  success,
  ErrorCodes,
  ErrorMessages,
} from '../utils/responses.js';
import { sendVerificationEmail, sendPasswordResetEmail } from '../services/email.js';
import { trackAffiliateSignup } from '../services/affiliate.js';
import { trackFailedLogin, clearFailedLogins } from '../services/security.js';

const auth = new Hono<HonoEnv>();

/**
 * POST /auth/signup
 *
 * Create a new user account with email verification
 *
 * Request body:
 * - email: string (required)
 * - password: string (required, 8+ chars with uppercase, lowercase, number, special char)
 * - firstName: string (required)
 * - lastName: string (required)
 * - companyName: string (optional)
 * - affiliateCode: string (optional)
 *
 * Response:
 * - 201: User created successfully with token
 * - 409: Email already exists
 * - 400: Validation error
 */
auth.post('/signup', validate(signupSchema), async (c) => {
  console.log('[Auth] ===== SIGNUP REQUEST RECEIVED =====');

  const data = c.get('validatedData') as {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    companyName?: string;
    affiliateCode?: string;
  };

  console.log('[Auth] Validated data:', {
    email: data.email,
    firstName: data.firstName,
    lastName: data.lastName,
    hasCompanyName: !!data.companyName
  });

  const db = c.get('db');

  try {
    console.log('[Auth] Checking if email exists...');
    // Check if email already exists
    const existingUser = await db.query('SELECT 1 FROM users WHERE email = $1', [
      data.email,
    ]);

    console.log('[Auth] Email check complete. Exists:', existingUser.rowCount > 0);

    if (existingUser.rowCount > 0) {
      console.log('[Auth] Email already exists, returning conflict');
      return conflict(c, ErrorCodes.EMAIL_EXISTS, ErrorMessages.EMAIL_EXISTS);
    }

    console.log('[Auth] Hashing password...');
    // Hash password using Argon2id
    const passwordHash = await hashPassword(data.password);
    console.log('[Auth] Password hashed successfully');

    // Insert user into database
    // Note: support_key is auto-generated by the database trigger
    // Note: charity_id removed - charity selections are stored in user_charity_selections table
    console.log('[Auth] Inserting user into database...');
    console.log('[Auth] INSERT params:', {
      email: data.email,
      firstName: data.firstName,
      lastName: data.lastName,
      hasCompanyName: !!data.companyName,
    });

    const result = await db.query(
      `
      INSERT INTO users (email, password_hash, first_name, last_name, company_name)
      VALUES ($1, $2, $3, $4, $5)
      RETURNING id, email, first_name, last_name, support_key, email_verified, created_at
      `,
      [
        data.email,
        passwordHash,
        data.firstName,
        data.lastName,
        data.companyName || null,
      ]
    );

    console.log('[Auth] User inserted successfully. Rows returned:', result.rowCount);

    const user = result.rows[0];
    console.log('[Auth] User data:', { id: user.id, email: user.email, supportKey: user.support_key });

    // Track affiliate if provided
    if (data.affiliateCode) {
      // Don't await - run in background, don't block signup
      trackAffiliateSignup(db, user.id, data.affiliateCode).catch((error) => {
        console.error('[Auth] Error tracking affiliate:', error);
      });
    }

    // Generate JWT token
    const token = await generateUserToken(user.id, user.email);

    // Send verification email (async, don't block)
    sendVerificationEmail(user.email, user.id, user.first_name).catch((error) => {
      console.error('[Auth] Error sending verification email:', error);
    });

    // Create audit log entry
    const ipAddress =
      c.req.header('x-forwarded-for') ||
      c.req.header('x-real-ip') ||
      c.req.header('cf-connecting-ip') ||
      null;

    await db.query(
      `
      INSERT INTO admin_audit_log (action, resource_type, resource_id, ip_address)
      VALUES ('user_signup', 'user', $1, $2)
      `,
      [user.id, ipAddress]
    );

    // Return success response
    return created(
      c,
      {
        user: {
          id: user.id,
          email: user.email,
          firstName: user.first_name,
          lastName: user.last_name,
          supportKey: user.support_key,
          emailVerified: user.email_verified,
          createdAt: user.created_at,
        },
        token,
      },
      'Account created successfully. Please check your email to verify.'
    );
  } catch (error) {
    console.error('[Auth] ===== SIGNUP ERROR =====');
    console.error('[Auth] Error type:', error instanceof Error ? error.constructor.name : typeof error);
    console.error('[Auth] Error message:', error instanceof Error ? error.message : String(error));
    console.error('[Auth] Error stack:', error instanceof Error ? error.stack : 'No stack trace');
    console.error('[Auth] Full error object:', error);
    console.error('[Auth] ===========================');
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * POST /auth/login
 *
 * Authenticate user and return JWT token
 *
 * TODO: Implement in Task 1.2
 */
auth.post('/login', async (c) => {
  return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'Not implemented yet');
});

/**
 * POST /auth/verify-email
 *
 * Verify user's email address using token from email
 *
 * TODO: Implement in Task 1.4
 */
auth.post('/verify-email', async (c) => {
  return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'Not implemented yet');
});

/**
 * POST /auth/forgot-password
 *
 * Request a password reset email
 *
 * Security: Always returns success to prevent email enumeration
 *
 * Request body:
 * - email: string (required)
 *
 * Response:
 * - 200: Success message (even if email doesn't exist)
 */
auth.post('/forgot-password', validate(passwordResetRequestSchema), async (c) => {
  const { email } = c.get('validatedData') as { email: string };
  const db = c.get('db');

  // CRITICAL: Always return the same success response to prevent email enumeration
  const successResponse = success(c, {
    message:
      'If that email address is in our system, we sent you a link to reset your password. Please check your inbox.',
  });

  try {
    // Look up user by email (only active accounts)
    const result = await db.query(
      'SELECT id, email, first_name FROM users WHERE email = $1 AND account_status = $2',
      [email, 'active']
    );

    // If user doesn't exist or account is not active, still return success
    if (result.rowCount === 0) {
      return successResponse;
    }

    const user = result.rows[0];

    // Generate cryptographically secure reset token (32 bytes = 64 hex chars)
    const token = crypto.randomBytes(32).toString('hex');
    const expiresAt = new Date(Date.now() + 60 * 60 * 1000); // 1 hour from now

    // Store token in database
    await db.query(
      `
      INSERT INTO password_reset_tokens (user_id, token, expires_at)
      VALUES ($1, $2, $3)
      `,
      [user.id, token, expiresAt]
    );

    // Send password reset email (async, don't block response)
    sendPasswordResetEmail(user.email, user.id, user.first_name).catch((error) => {
      console.error('[Auth] Error sending password reset email:', error);
    });

    // Create audit log entry
    const ipAddress =
      c.req.header('x-forwarded-for') ||
      c.req.header('x-real-ip') ||
      c.req.header('cf-connecting-ip') ||
      null;

    await db.query(
      `
      INSERT INTO admin_audit_log (action, resource_type, resource_id, ip_address)
      VALUES ('password_reset_requested', 'user', $1, $2)
      `,
      [user.id, ipAddress]
    );

    return successResponse;
  } catch (error) {
    console.error('[Auth] Forgot password error:', error);
    // Still return success response to avoid leaking information
    return successResponse;
  }
});

/**
 * POST /auth/reset-password
 *
 * Reset password using token from email
 *
 * Request body:
 * - token: string (required) - Reset token from email
 * - password: string (required) - New password
 *
 * Response:
 * - 200: Password reset successfully
 * - 400: Invalid or expired token
 */
auth.post('/reset-password', validate(passwordResetSchema), async (c) => {
  const { token, password } = c.get('validatedData') as {
    token: string;
    password: string;
  };
  const db = c.get('db');

  try {
    // Look up reset token
    const tokenResult = await db.query(
      `
      SELECT id, user_id, expires_at, used_at
      FROM password_reset_tokens
      WHERE token = $1
      `,
      [token]
    );

    // Token doesn't exist
    if (tokenResult.rowCount === 0) {
      return badRequest(
        c,
        ErrorCodes.INVALID_TOKEN,
        'That reset link is invalid or has expired. Please request a new one.'
      );
    }

    const resetToken = tokenResult.rows[0];
    const now = new Date();

    // Check if token has expired
    if (now > new Date(resetToken.expires_at)) {
      return badRequest(
        c,
        ErrorCodes.INVALID_TOKEN,
        'That reset link has expired. Please request a new one.'
      );
    }

    // Check if token has already been used
    if (resetToken.used_at) {
      return badRequest(
        c,
        ErrorCodes.INVALID_TOKEN,
        'That reset link has already been used. Please request a new one if needed.'
      );
    }

    // Hash the new password
    const passwordHash = await hashPassword(password);

    // Update password and mark token as used in a transaction
    await db.query('BEGIN');

    try {
      // Update user's password
      await db.query(
        `
        UPDATE users
        SET password_hash = $1, updated_at = NOW()
        WHERE id = $2
        `,
        [passwordHash, resetToken.user_id]
      );

      // Mark token as used
      await db.query(
        `
        UPDATE password_reset_tokens
        SET used_at = NOW()
        WHERE id = $1
        `,
        [resetToken.id]
      );

      // Create audit log entry
      const ipAddress =
        c.req.header('x-forwarded-for') ||
        c.req.header('x-real-ip') ||
        c.req.header('cf-connecting-ip') ||
        null;

      await db.query(
        `
        INSERT INTO admin_audit_log (action, resource_type, resource_id, ip_address)
        VALUES ('password_reset_completed', 'user', $1, $2)
        `,
        [resetToken.user_id, ipAddress]
      );

      await db.query('COMMIT');

      return success(c, {
        message:
          'Your password has been reset successfully. You can now log in with your new password.',
      });
    } catch (error) {
      await db.query('ROLLBACK');
      throw error;
    }
  } catch (error) {
    console.error('[Auth] Reset password error:', error);
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

export default auth;
