/**
 * Authentication routes for Audacious Money platform
 *
 * Handles user signup, login, email verification, and password reset
 */

import { Hono } from 'hono';
import crypto from 'crypto';
import type { HonoEnv } from '../types/hono.js';
import {
  validate,
  signupSchema,
  loginSchema,
  passwordResetRequestSchema,
  passwordResetSchema,
} from '../utils/validation.js';
import { hashPassword, timingSafeVerify } from '../utils/password.js';
import { generateUserToken } from '../utils/jwt.js';
import {
  created,
  conflict,
  badRequest,
  unauthorized,
  forbidden,
  success,
  notFound,
  ErrorCodes,
  ErrorMessages,
} from '../utils/responses.js';
import { sendVerificationEmail, sendPasswordResetEmail, sendAccountReactivatedEmail, sendCPGLaunchSignupEmail, sendHomeEmailSignupEmail, sendBookkeepingSignupEmail } from '../services/email.service.js';
import { trackAffiliateSignup } from '../services/affiliate.js';
import { trackFailedLogin, clearFailedLogins } from '../services/security.js';

const auth = new Hono<HonoEnv>();

/**
 * POST /auth/signup
 *
 * Create a new user account with email verification
 *
 * Request body:
 * - email: string (required)
 * - password: string (required, 8+ chars with uppercase, lowercase, number, special char)
 * - firstName: string (required)
 * - lastName: string (required)
 * - companyName: string (optional)
 * - affiliateCode: string (optional)
 *
 * Response:
 * - 201: User created successfully with token
 * - 409: Email already exists
 * - 400: Validation error
 */
auth.post('/signup', validate(signupSchema), async (c) => {
  console.log('[Auth] ===== SIGNUP REQUEST RECEIVED =====');

  const data = c.get('validatedData') as {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    companyName?: string;
    affiliateCode?: string;
  };

  console.log('[Auth] Validated data:', {
    email: data.email,
    firstName: data.firstName,
    lastName: data.lastName,
    hasCompanyName: !!data.companyName
  });

  const db = c.get('db');

  try {
    console.log('[Auth] Checking if email exists...');
    // Check if email already exists
    const existingUser = await db.query('SELECT 1 FROM users WHERE email = $1', [
      data.email,
    ]);

    console.log('[Auth] Email check complete. Exists:', existingUser.rowCount > 0);

    if (existingUser.rowCount > 0) {
      console.log('[Auth] Email already exists, returning conflict');
      return conflict(c, ErrorCodes.EMAIL_EXISTS, ErrorMessages.EMAIL_EXISTS);
    }

    console.log('[Auth] Hashing password...');
    // Hash password using Argon2id
    const passwordHash = await hashPassword(data.password);
    console.log('[Auth] Password hashed successfully');

    // Insert user into database
    // Note: support_key is auto-generated by the database trigger
    // Note: charity_id removed - charity selections are stored in user_charity_selections table
    console.log('[Auth] Inserting user into database...');
    console.log('[Auth] INSERT params:', {
      email: data.email,
      firstName: data.firstName,
      lastName: data.lastName,
      hasCompanyName: !!data.companyName,
    });

    const result = await db.query(
      `
      INSERT INTO users (email, password_hash, first_name, last_name, company_name)
      VALUES ($1, $2, $3, $4, $5)
      RETURNING id, email, first_name, last_name, company_name, support_key, email_verified, account_status, created_at
      `,
      [
        data.email,
        passwordHash,
        data.firstName,
        data.lastName,
        data.companyName || null,
      ]
    );

    console.log('[Auth] User inserted successfully. Rows returned:', result.rowCount);

    const user = result.rows[0];
    console.log('[Auth] User data:', {
      id: user.id,
      email: user.email,
      supportKey: user.support_key,
      accountStatus: user.account_status
    });

    // Track affiliate if provided
    if (data.affiliateCode) {
      // Don't await - run in background, don't block signup
      trackAffiliateSignup(db, user.id, data.affiliateCode).catch((error) => {
        console.error('[Auth] Error tracking affiliate:', error);
      });
    }

    // Generate JWT token
    const token = await generateUserToken(user.id, user.email);

    // Send verification email (async, don't block)
    sendVerificationEmail(user.email, user.id, user.first_name).catch((error) => {
      console.error('[Auth] Error sending verification email:', error);
    });

    // Create audit log entry
    // x-forwarded-for can contain multiple IPs (client, proxy1, proxy2)
    // Extract just the first IP (the actual client IP)
    const ipAddressRaw =
      c.req.header('x-forwarded-for') ||
      c.req.header('x-real-ip') ||
      c.req.header('cf-connecting-ip') ||
      '';
    const ipAddress = ipAddressRaw.split(',')[0].trim() || null;

    await db.query(
      `
      INSERT INTO admin_audit_log (action, resource_type, resource_id, ip_address)
      VALUES ('user_signup', 'user', $1, $2)
      `,
      [user.id, ipAddress]
    );

    // Return success response
    return created(
      c,
      {
        user: {
          id: user.id,
          email: user.email,
          firstName: user.first_name,
          lastName: user.last_name,
          companyName: user.company_name,
          supportKey: user.support_key,
          emailVerified: user.email_verified,
          createdAt: user.created_at,
        },
        token,
      },
      'Account created successfully. Please check your email to verify.'
    );
  } catch (error) {
    console.error('[Auth] ===== SIGNUP ERROR =====');
    console.error('[Auth] Error type:', error instanceof Error ? error.constructor.name : typeof error);
    console.error('[Auth] Error message:', error instanceof Error ? error.message : String(error));
    console.error('[Auth] Error stack:', error instanceof Error ? error.stack : 'No stack trace');
    console.error('[Auth] Full error object:', error);
    console.error('[Auth] ===========================');
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * POST /auth/login
 *
 * Authenticate user and return JWT token
 *
 * Request body:
 * - email: string (required)
 * - password: string (required)
 *
 * Response:
 * - 200: Login successful with token
 * - 401: Invalid credentials
 * - 403: Account inactive or locked
 */
auth.post('/login', validate(loginSchema), async (c) => {
  const { email, password } = c.get('validatedData') as {
    email: string;
    password: string;
  };
  const db = c.get('db');

  try {
    // Look up user by email
    const result = await db.query(
      `SELECT id, email, password_hash, first_name, last_name, company_name, account_status, email_verified
       FROM users
       WHERE email = $1`,
      [email]
    );

    // User not found
    if (result.rowCount === 0) {
      // Track failed login attempt
      const ipAddress =
        c.req.header('x-forwarded-for')?.split(',')[0].trim() ||
        c.req.header('x-real-ip') ||
        c.req.header('cf-connecting-ip') ||
        '';
      await trackFailedLogin(db, email, ipAddress);
      return unauthorized(c, ErrorCodes.INVALID_CREDENTIALS, ErrorMessages.INVALID_CREDENTIALS);
    }

    const user = result.rows[0];
    console.log(`[Auth] Login attempt for user ${user.id} (${user.email}) - account_status: ${user.account_status}`);

    // Verify password using timing-safe comparison (do this before account status check)
    const isValidPassword = await timingSafeVerify(password, user.password_hash);

    if (!isValidPassword) {
      // Track failed login attempt
      const ipAddress =
        c.req.header('x-forwarded-for')?.split(',')[0].trim() ||
        c.req.header('x-real-ip') ||
        c.req.header('cf-connecting-ip') ||
        '';
      await trackFailedLogin(db, email, ipAddress);
      return unauthorized(c, ErrorCodes.INVALID_CREDENTIALS, ErrorMessages.INVALID_CREDENTIALS);
    }

    // Handle suspended accounts - automatically reactivate on successful login
    if (user.account_status === 'suspended') {
      console.log(`[Auth] Reactivating suspended account: ${user.id} (${user.email})`);

      await db.query(
        `UPDATE users
         SET account_status = 'active', updated_at = NOW()
         WHERE id = $1`,
        [user.id]
      );

      const ipAddress =
        c.req.header('x-forwarded-for')?.split(',')[0].trim() ||
        c.req.header('x-real-ip') ||
        c.req.header('cf-connecting-ip') ||
        '';

      await db.query(
        `INSERT INTO admin_audit_log (action, resource_type, resource_id, old_values, new_values, ip_address)
         VALUES ('account_reactivated', 'user', $1, $2, $3, $4)`,
        [
          user.id,
          JSON.stringify({ account_status: 'suspended' }),
          JSON.stringify({ account_status: 'active' }),
          ipAddress,
        ]
      );

      // Update user object for the rest of the login flow
      user.account_status = 'active';

      // Send reactivation email
      try {
        await sendAccountReactivatedEmail(user.email, user.first_name);
      } catch (emailError) {
        console.error('[Auth] Failed to send account reactivated email:', emailError);
        // Don't fail the login if email fails
      }

      console.log(`[Auth] Account reactivated successfully: ${user.id}`);
    }

    // Check if account is active (after potential reactivation)
    console.log(`[Auth] Checking account_status for user ${user.id}: '${user.account_status}' (type: ${typeof user.account_status})`);
    if (user.account_status !== 'active') {
      console.log(`[Auth] BLOCKED LOGIN - account_status is not 'active': '${user.account_status}'`);
      return forbidden(
        c,
        ErrorCodes.ACCOUNT_INACTIVE,
        'Your account is not active. Please contact support for assistance.'
      );
    }
    console.log(`[Auth] Account status check passed for user ${user.id}`);


    // Clear any failed login attempts
    await clearFailedLogins(db, email);

    // Generate JWT token
    const token = await generateUserToken(user.id, user.email);

    // Get user's products
    const productsResult = await db.query(
      `SELECT up.product_id, up.status, p.name, p.slug
       FROM user_products up
       JOIN products p ON up.product_id = p.id
       WHERE up.user_id = $1 AND up.status IN ('trial', 'active')
       ORDER BY up.activated_at DESC`,
      [user.id]
    );

    console.log(`[Auth] Products query returned ${productsResult.rowCount} rows for user ${user.id}`);

    const products = productsResult.rows.map((row) => ({
      id: row.product_id,
      name: row.name,
      slug: row.slug,
      status: row.status,
    }));

    console.log(`[Auth] Products for user ${user.id}:`, products);

    // Update last login timestamp
    await db.query('UPDATE users SET last_login_at = NOW() WHERE id = $1', [user.id]);

    // Create audit log entry
    const ipAddress =
      c.req.header('x-forwarded-for')?.split(',')[0].trim() ||
      c.req.header('x-real-ip') ||
      c.req.header('cf-connecting-ip') ||
      '';

    await db.query(
      `INSERT INTO admin_audit_log (action, resource_type, resource_id, ip_address)
       VALUES ('user_login', 'user', $1, $2)`,
      [user.id, ipAddress]
    );

    return success(c, {
      token,
      user: {
        id: user.id,
        email: user.email,
        firstName: user.first_name,
        lastName: user.last_name,
        companyName: user.company_name,
        emailVerified: user.email_verified,
      },
      products,
    });
  } catch (error) {
    console.error('[Auth] Login error:', error);
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * POST /auth/beta-signup
 *
 * Beta tester signup - creates account and grants immediate free access to CPG tool
 * No payment required, no trial period, instant activation
 *
 * Request body: Same as /auth/signup
 *
 * Response:
 * - 201: Account created with CPG access
 * - 409: Email already exists
 * - 400: Validation error
 */
auth.post('/beta-signup', validate(signupSchema), async (c) => {
  console.log('[Auth] ===== BETA SIGNUP REQUEST RECEIVED =====');

  const data = c.get('validatedData') as {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    companyName?: string;
    affiliateCode?: string;
  };

  console.log('[Auth] Beta signup data:', {
    email: data.email,
    firstName: data.firstName,
    lastName: data.lastName,
    hasCompanyName: !!data.companyName
  });

  const db = c.get('db');

  try {
    // Check if email already exists
    const existingUser = await db.query('SELECT 1 FROM users WHERE email = $1', [
      data.email,
    ]);

    if (existingUser.rowCount > 0) {
      console.log('[Auth] Email already exists, returning conflict');
      return conflict(c, ErrorCodes.EMAIL_EXISTS, ErrorMessages.EMAIL_EXISTS);
    }

    // Hash password
    const passwordHash = await hashPassword(data.password);

    // Insert user into database
    const userResult = await db.query(
      `
      INSERT INTO users (email, password_hash, first_name, last_name, company_name)
      VALUES ($1, $2, $3, $4, $5)
      RETURNING id, email, first_name, last_name, company_name, support_key, email_verified, created_at
      `,
      [
        data.email,
        passwordHash,
        data.firstName,
        data.lastName,
        data.companyName || null,
      ]
    );

    const user = userResult.rows[0];
    console.log('[Auth] Beta user created:', { id: user.id, email: user.email, supportKey: user.support_key });

    // Get CPG product
    const productResult = await db.query(
      `SELECT id, name FROM products WHERE slug = $1`,
      ['cpu-cpg-calculator']
    );

    if (productResult.rowCount === 0) {
      console.error('[Auth] CPG product not found!');
      return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'Product configuration error');
    }

    const cpgProduct = productResult.rows[0];

    // Auto-assign CPG product with active status (beta testers get free access)
    await db.query(
      `
      INSERT INTO user_products (user_id, product_id, status, activated_at)
      VALUES ($1, $2, 'active', NOW())
      `,
      [user.id, cpgProduct.id]
    );

    console.log('[Auth] CPG product assigned to beta user');

    // Track affiliate if provided
    if (data.affiliateCode) {
      trackAffiliateSignup(db, user.id, data.affiliateCode).catch((error) => {
        console.error('[Auth] Error tracking affiliate:', error);
      });
    }

    // Generate JWT token
    const token = await generateUserToken(user.id, user.email);

    // Send verification email (async, don't block)
    sendVerificationEmail(user.email, user.id, user.first_name).catch((error) => {
      console.error('[Auth] Error sending verification email:', error);
    });

    // Create audit log entry
    const ipAddressRaw =
      c.req.header('x-forwarded-for') ||
      c.req.header('x-real-ip') ||
      c.req.header('cf-connecting-ip') ||
      '';
    const ipAddress = ipAddressRaw.split(',')[0].trim() || null;

    await db.query(
      `
      INSERT INTO admin_audit_log (action, resource_type, resource_id, ip_address)
      VALUES ('beta_signup', 'user', $1, $2)
      `,
      [user.id, ipAddress]
    );

    console.log('[Auth] Beta signup complete!');

    // Return success response
    return created(
      c,
      {
        user: {
          id: user.id,
          email: user.email,
          firstName: user.first_name,
          lastName: user.last_name,
          companyName: user.company_name,
          supportKey: user.support_key,
          emailVerified: user.email_verified,
          createdAt: user.created_at,
        },
        token,
        cpgProduct: {
          id: cpgProduct.id,
          name: cpgProduct.name,
        },
      },
      'Welcome to the beta! Your CPG tool access is ready.'
    );
  } catch (error) {
    console.error('[Auth] ===== BETA SIGNUP ERROR =====');
    console.error('[Auth] Error:', error);
    console.error('[Auth] ===========================');
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * POST /auth/verify-email
 *
 * Verify user's email address using token from email
 *
 * TODO: Implement in Task 1.4
 */
auth.post('/verify-email', async (c) => {
  return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'Not implemented yet');
});

/**
 * POST /auth/forgot-password
 *
 * Request a password reset email
 *
 * Security: Always returns success to prevent email enumeration
 *
 * Request body:
 * - email: string (required)
 *
 * Response:
 * - 200: Success message (even if email doesn't exist)
 */
auth.post('/forgot-password', validate(passwordResetRequestSchema), async (c) => {
  const { email } = c.get('validatedData') as { email: string };
  const db = c.get('db');

  // CRITICAL: Always return the same success response to prevent email enumeration
  const successResponse = success(c, {
    message:
      'If that email address is in our system, we sent you a link to reset your password. Please check your inbox.',
  });

  try {
    // Look up user by email (only active accounts)
    const result = await db.query(
      'SELECT id, email, first_name FROM users WHERE email = $1 AND account_status = $2',
      [email, 'active']
    );

    // If user doesn't exist or account is not active, still return success
    if (result.rowCount === 0) {
      return successResponse;
    }

    const user = result.rows[0];

    // Generate cryptographically secure reset token (32 bytes = 64 hex chars)
    const token = crypto.randomBytes(32).toString('hex');
    const expiresAt = new Date(Date.now() + 60 * 60 * 1000); // 1 hour from now

    // Store token in database
    await db.query(
      `
      INSERT INTO password_reset_tokens (user_id, token, expires_at)
      VALUES ($1, $2, $3)
      `,
      [user.id, token, expiresAt]
    );

    // Send password reset email (async, don't block response)
    const appUrl = process.env.FRONTEND_URL || 'https://app.audacious.money';
    sendPasswordResetEmail(user.email, token, appUrl).catch((error) => {
      console.error('[Auth] Error sending password reset email:', error);
    });

    // Create audit log entry
    // x-forwarded-for can contain multiple IPs (client, proxy1, proxy2)
    // Extract just the first IP (the actual client IP)
    const ipAddressRaw =
      c.req.header('x-forwarded-for') ||
      c.req.header('x-real-ip') ||
      c.req.header('cf-connecting-ip') ||
      '';
    const ipAddress = ipAddressRaw.split(',')[0].trim() || null;

    await db.query(
      `
      INSERT INTO admin_audit_log (action, resource_type, resource_id, ip_address)
      VALUES ('password_reset_requested', 'user', $1, $2)
      `,
      [user.id, ipAddress]
    );

    return successResponse;
  } catch (error) {
    console.error('[Auth] Forgot password error:', error);
    // Still return success response to avoid leaking information
    return successResponse;
  }
});

/**
 * POST /auth/reset-password
 *
 * Reset password using token from email
 *
 * Request body:
 * - token: string (required) - Reset token from email
 * - password: string (required) - New password
 *
 * Response:
 * - 200: Password reset successfully
 * - 400: Invalid or expired token
 */
auth.post('/reset-password', validate(passwordResetSchema), async (c) => {
  const { token, password } = c.get('validatedData') as {
    token: string;
    password: string;
  };
  const db = c.get('db');

  try {
    // Look up reset token
    const tokenResult = await db.query(
      `
      SELECT id, user_id, expires_at, used_at
      FROM password_reset_tokens
      WHERE token = $1
      `,
      [token]
    );

    // Token doesn't exist
    if (tokenResult.rowCount === 0) {
      return badRequest(
        c,
        ErrorCodes.INVALID_TOKEN,
        'That reset link is invalid or has expired. Please request a new one.'
      );
    }

    const resetToken = tokenResult.rows[0];
    const now = new Date();

    // Check if token has expired
    if (now > new Date(resetToken.expires_at)) {
      return badRequest(
        c,
        ErrorCodes.INVALID_TOKEN,
        'That reset link has expired. Please request a new one.'
      );
    }

    // Check if token has already been used
    if (resetToken.used_at) {
      return badRequest(
        c,
        ErrorCodes.INVALID_TOKEN,
        'That reset link has already been used. Please request a new one if needed.'
      );
    }

    // Hash the new password
    const passwordHash = await hashPassword(password);

    // Update password and mark token as used in a transaction
    await db.query('BEGIN');

    try {
      // Update user's password
      await db.query(
        `
        UPDATE users
        SET password_hash = $1, updated_at = NOW()
        WHERE id = $2
        `,
        [passwordHash, resetToken.user_id]
      );

      // Mark token as used
      await db.query(
        `
        UPDATE password_reset_tokens
        SET used_at = NOW()
        WHERE id = $1
        `,
        [resetToken.id]
      );

      // Create audit log entry
      const ipAddressRaw =
        c.req.header('x-forwarded-for') ||
        c.req.header('x-real-ip') ||
        c.req.header('cf-connecting-ip') ||
        '';
      const ipAddress = ipAddressRaw.split(',')[0].trim() || null;

      await db.query(
        `
        INSERT INTO admin_audit_log (action, resource_type, resource_id, ip_address)
        VALUES ('password_reset_completed', 'user', $1, $2)
        `,
        [resetToken.user_id, ipAddress]
      );

      await db.query('COMMIT');

      return success(c, {
        message:
          'Your password has been reset successfully. You can now log in with your new password.',
      });
    } catch (error) {
      await db.query('ROLLBACK');
      throw error;
    }
  } catch (error) {
    console.error('[Auth] Reset password error:', error);
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * POST /auth/cpg-launch-signup
 *
 * Sign up for CPG Product Costing Tool launch notifications
 * No account creation - just email collection for May 4th, 2026 launch
 *
 * Request body:
 * - email: string (required)
 * - firstName: string (required)
 * - lastName: string (required)
 * - business: string (optional) - Business name
 *
 * Response:
 * - 201: Signup successful, confirmation email sent
 * - 409: Email already signed up
 * - 400: Validation error
 */
auth.post('/cpg-launch-signup', async (c) => {
  const db = c.get('db');

  try {
    const body = await c.req.json();
    const { email, firstName, lastName, business } = body;

    // Basic validation
    if (!email || !firstName || !lastName) {
      return badRequest(c, ErrorCodes.VALIDATION_ERROR, 'Email, first name, and last name are required');
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return badRequest(c, ErrorCodes.VALIDATION_ERROR, 'Invalid email format');
    }

    // Check if email already signed up
    const existingSignup = await db.query(
      'SELECT id, unsubscribed_at FROM cpg_launch_signups WHERE email = $1',
      [email]
    );

    let signupId: string;

    if (existingSignup.rowCount > 0) {
      const existing = existingSignup.rows[0];

      // If they previously unsubscribed, allow them to re-subscribe
      if (existing.unsubscribed_at) {
        await db.query(
          `UPDATE cpg_launch_signups
           SET first_name = $1, last_name = $2, business_name = $3,
               unsubscribed_at = NULL, created_at = NOW()
           WHERE email = $4`,
          [firstName, lastName, business || null, email]
        );

        signupId = existing.id;

        console.log('[Auth] CPG launch re-subscription:', { email, firstName });
      } else {
        // Still subscribed - don't allow duplicate signup
        return conflict(c, 'EMAIL_EXISTS', 'This email is already on the launch list');
      }
    } else {
      // New signup - insert into database
      const insertResult = await db.query(
        `INSERT INTO cpg_launch_signups (email, first_name, last_name, business_name)
         VALUES ($1, $2, $3, $4)
         RETURNING id`,
        [email, firstName, lastName, business || null]
      );

      signupId = insertResult.rows[0].id;

      console.log('[Auth] CPG launch signup:', { email, firstName });
    }

    // Send confirmation email (async, don't block response)
    sendCPGLaunchSignupEmail(email, firstName, signupId).catch((error) => {
      console.error('[Auth] Error sending CPG launch signup email:', error);
    });

    return created(c, {}, 'Thanks for signing up! Check your email for confirmation.');
  } catch (error) {
    console.error('[Auth] CPG launch signup error:', error);
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * GET /auth/cpg-signup-info/:signupId
 *
 * Get CPG launch signup information for unsubscribe form
 */
auth.get('/cpg-signup-info/:signupId', async (c) => {
  const { signupId } = c.req.param();
  const db = c.get('db');

  try {
    const result = await db.query(
      'SELECT id, email, first_name, unsubscribed_at FROM cpg_launch_signups WHERE id = $1',
      [signupId]
    );

    if (result.rowCount === 0) {
      return notFound(c, ErrorCodes.NOT_FOUND, 'Signup not found');
    }

    const signup = result.rows[0];

    return success(c, {
      email: signup.email,
      firstName: signup.first_name,
      unsubscribedAt: signup.unsubscribed_at
    });
  } catch (error) {
    console.error('[Auth] CPG signup info error:', error);
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * POST /auth/cpg-unsubscribe
 *
 * Unsubscribe from CPG Product Costing Tool launch notifications
 * Marks the signup as unsubscribed but keeps the record
 */
auth.post('/cpg-unsubscribe', async (c) => {
  const db = c.get('db');

  try {
    const body = await c.req.json();
    const { signupId } = body;

    if (!signupId) {
      return badRequest(c, ErrorCodes.VALIDATION_ERROR, 'Signup ID is required');
    }

    // Check if signup exists
    const result = await db.query(
      'SELECT id, email, first_name, unsubscribed_at FROM cpg_launch_signups WHERE id = $1',
      [signupId]
    );

    if (result.rowCount === 0) {
      return notFound(c, ErrorCodes.NOT_FOUND, 'Signup not found');
    }

    const signup = result.rows[0];

    // Check if already unsubscribed
    if (signup.unsubscribed_at) {
      return success(c, {
        message: 'You were already unsubscribed from CPG launch notifications.'
      });
    }

    // Mark as unsubscribed
    await db.query(
      'UPDATE cpg_launch_signups SET unsubscribed_at = NOW() WHERE id = $1',
      [signupId]
    );

    console.log('[Auth] CPG launch unsubscribe:', { email: signup.email, signupId });

    return success(c, {
      message: 'You have been unsubscribed from CPG Product Costing Tool launch notifications.'
    });
  } catch (error) {
    console.error('[Auth] CPG unsubscribe error:', error);
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * POST /auth/home-email-signup
 *
 * Sign up for home page email waitlist (full bookkeeping suite)
 *
 * Request body:
 * - email: string (required)
 * - firstName: string (required)
 * - lastName: string (required)
 *
 * Response:
 * - 201: Signup successful
 * - 409: Email already signed up
 * - 400: Validation error
 */
auth.post('/home-email-signup', async (c) => {
  const db = c.get('db');

  try {
    const body = await c.req.json();
    const { email, firstName, lastName } = body;

    // Basic validation
    if (!email || !firstName || !lastName) {
      return badRequest(c, ErrorCodes.VALIDATION_ERROR, 'Email, first name, and last name are required');
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return badRequest(c, ErrorCodes.VALIDATION_ERROR, 'Invalid email format');
    }

    // Check if email already signed up
    const existingSignup = await db.query(
      'SELECT id, unsubscribed_at FROM home_email_signups WHERE email = $1',
      [email]
    );

    let signupId: string;

    if (existingSignup.rowCount > 0) {
      const existing = existingSignup.rows[0];

      // If they previously unsubscribed, allow them to re-subscribe
      if (existing.unsubscribed_at) {
        await db.query(
          `UPDATE home_email_signups
           SET first_name = $1, last_name = $2,
               unsubscribed_at = NULL, created_at = NOW()
           WHERE email = $3`,
          [firstName, lastName, email]
        );

        signupId = existing.id;

        console.log('[Auth] Home email re-subscription:', { email, firstName });
      } else {
        // Still subscribed - don't allow duplicate signup
        return conflict(c, 'EMAIL_EXISTS', 'This email is already on the waitlist');
      }
    } else {
      // New signup - insert into database
      const insertResult = await db.query(
        `INSERT INTO home_email_signups (email, first_name, last_name)
         VALUES ($1, $2, $3)
         RETURNING id`,
        [email, firstName, lastName]
      );

      signupId = insertResult.rows[0].id;

      console.log('[Auth] Home email signup:', { email, firstName });
    }

    // Send confirmation email (async, don't block response)
    sendHomeEmailSignupEmail(email, firstName, signupId).catch((error) => {
      console.error('[Auth] Error sending home email signup email:', error);
    });

    return created(c, {}, 'Thanks for signing up! Check your email for confirmation.');
  } catch (error) {
    console.error('[Auth] Home email signup error:', error);
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

/**
 * POST /auth/bookkeeping-signup
 *
 * Sign up for bookkeeping suite waitlist
 *
 * Request body:
 * - email: string (required)
 * - firstName: string (required)
 * - lastName: string (required)
 *
 * Response:
 * - 201: Signup successful
 * - 409: Email already signed up
 * - 400: Validation error
 */
auth.post('/bookkeeping-signup', async (c) => {
  const db = c.get('db');

  try {
    const body = await c.req.json();
    const { email, firstName, lastName } = body;

    // Basic validation
    if (!email || !firstName || !lastName) {
      return badRequest(c, ErrorCodes.VALIDATION_ERROR, 'Email, first name, and last name are required');
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return badRequest(c, ErrorCodes.VALIDATION_ERROR, 'Invalid email format');
    }

    // Check if email already signed up
    const existingSignup = await db.query(
      'SELECT id, unsubscribed_at FROM bookkeeping_signups WHERE email = $1',
      [email]
    );

    let signupId: string;

    if (existingSignup.rowCount > 0) {
      const existing = existingSignup.rows[0];

      // If they previously unsubscribed, allow them to re-subscribe
      if (existing.unsubscribed_at) {
        await db.query(
          `UPDATE bookkeeping_signups
           SET first_name = $1, last_name = $2,
               unsubscribed_at = NULL, created_at = NOW()
           WHERE email = $3`,
          [firstName, lastName, email]
        );

        signupId = existing.id;

        console.log('[Auth] Bookkeeping signup re-subscription:', { email, firstName });
      } else {
        // Still subscribed - don't allow duplicate signup
        return conflict(c, 'EMAIL_EXISTS', 'This email is already on the waitlist');
      }
    } else {
      // New signup - insert into database
      const insertResult = await db.query(
        `INSERT INTO bookkeeping_signups (email, first_name, last_name)
         VALUES ($1, $2, $3)
         RETURNING id`,
        [email, firstName, lastName]
      );

      signupId = insertResult.rows[0].id;

      console.log('[Auth] Bookkeeping signup:', { email, firstName });
    }

    // Send confirmation email (async, don't block response)
    sendBookkeepingSignupEmail(email, firstName, signupId).catch((error) => {
      console.error('[Auth] Error sending bookkeeping signup email:', error);
    });

    return created(c, {}, 'Thanks for signing up! Check your email for confirmation.');
  } catch (error) {
    console.error('[Auth] Bookkeeping signup error:', error);
    return badRequest(c, ErrorCodes.INTERNAL_ERROR, 'An unexpected error occurred');
  }
});

export default auth;
